// Single source of truth for all IPC channel names.
// Import this in both preload and renderer to keep types in sync.

export const IPC = {
  settings: {
    get: 'settings:get',
    set: 'settings:set',
    onChange: 'settings:onChange',
  },
  audit: {
    query: 'audit:query',
  },
  window: {
    minimize: 'window:minimize',
    maximize: 'window:maximize',
    close: 'window:close',
    isMaximized: 'window:isMaximized',
  },
  app: {
    bootstrapInfo: 'app:bootstrapInfo',
  },
  project: {
    list: 'project:list',
    get: 'project:get',
    create: 'project:create',
    delete: 'project:delete',
    setStatus: 'project:setStatus',
    updateMeta: 'project:updateMeta',
    updatePermissions: 'project:updatePermissions',
    getOrchestration: 'project:getOrchestration',
    onStatusChanged: 'project:onStatusChanged',
    liveStats: 'project:live-stats',
    checkReadiness: 'project:check-readiness',
    listWorkflows: 'project:listWorkflows',
    listSteps: 'project:listSteps',
    listContextFiles: 'project:listContextFiles',
    readContextFile: 'project:readContextFile',
    writeContextFile: 'project:writeContextFile',
    deleteContextFile: 'project:deleteContextFile',
    export: 'project:export',
    import: 'project:import',
    importCommit: 'project:importCommit',
    importAbort: 'project:importAbort',
    openExample: 'project:openExample',
  },
  usage: {
    get: 'usage:get',
  },
  adapters: {
    list: 'adapters:list',
    detect: 'adapters:detect',
    listModels: 'adapters:listModels',
    listEfforts: 'adapters:listEfforts',
    getUsage: 'adapters:getUsage',
    onUsageUpdate: 'adapters:onUsageUpdate',
    checkProviderReady: 'adapters:checkProviderReady',
  },
  adapter: {
    checkReadiness: 'adapter:check-readiness',
    recheck: 'adapter:recheck',
    getCached: 'adapter:get-cached',
    onReadinessChanged: 'adapter:readiness-changed',
  },
  step: {
    addTray: 'step:addTray',
    addWorker: 'step:addWorker',
    addSource: 'step:addSource',
    addOutlet: 'step:addOutlet',
    update: 'step:update',
    delete: 'step:delete',
    readProcess: 'step:readProcess',
    updateProcess: 'step:updateProcess',
    moveUp: 'step:moveUp',
  },
  worker: {
    triggerRun: 'worker:triggerRun',
    runNow: 'worker:runNow',
    listRuns: 'worker:listRuns',
    getRun: 'worker:getRun',
    readTerminalLog: 'worker:readTerminalLog',
    onRunEvent: 'worker:onRunEvent',
    sendInput: 'worker:sendInput',
    openExternalTerminal: 'worker:openExternalTerminal',
  },
  card: {
    list: 'card:list',
    get: 'card:get',
    counts: 'card:counts',
    create: 'card:create',
    markReady: 'card:markReady',
    archive: 'card:archive',
    retry: 'card:retry',
    edit: 'card:edit',
    sendBack: 'card:sendBack',
  },
  queue: {
    getPending: 'queue:getPending',
    onUpdate: 'queue:onUpdate',
  },
  source: {
    create: 'source:create',
    runNow: 'source:run-now',
    pause: 'source:pause',
    resume: 'source:resume',
    getState: 'source:get-state',
    listRuns: 'source:list-runs',
    resetDedup: 'source:reset-dedup',
    onRunEvent: 'source:run-event',
  },
  notifications: {
    getSettings: 'notifications:get-settings',
    updateSettings: 'notifications:update-settings',
    clearAllNotified: 'notifications:clear-all-notified',
    getBadgeCount: 'notifications:get-badge-count',
  },
  notification: {
    navigate: 'notification:navigate',
  },
  credential: {
    list:           'credential:list',
    get:            'credential:get',
    save:           'credential:save',
    delete:         'credential:delete',
    saveSecret:     'credential:save-secret',
    testConnection: 'credential:test-connection',
  },
  outlet: {
    runNow:      'outlet:run-now',
    listRuns:    'outlet:list-runs',
    onStarted:   'outlet:run-started',
    onCompleted: 'outlet:run-completed',
    onFailed:    'outlet:run-failed',
  },
  ai: {
    query:   'ai:query',
    abort:   'ai:abort',
    onChunk: 'ai:query-chunk',
  },
  aiLog: {
    getLines: 'ai-log:get-lines',
  },
} as const
